# Project info
site_name: Panlingue
site_description: An official description of the Panlingue language
site_author: Risto Kupsala et alia
site_url: https://www.pandunia.info/panlingue/
site_dir: ../html/panlingue
docs_dir: ./docs
use_directory_urls: false

# Repository
repo_name: 'panlingue'
repo_url: 'https://github.com/barumau/panlingue'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: CC-BY-SA-4.0

# Configuration
theme:
  name: material
#  custom_dir: overrides
  language: en
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

# Navigation
nav:
  - Home: index.md
  - Grammar:
    - 'The 12 rules': G-baze.md
    - 'World Words': L-lexe.md
    - 'Spelling and pronunciation': G-ABC.md
    - 'Regular Accent': 103_aksente.md
    - 'Word classes': G-PoS.md
    - Pronouns: G-PRO.md
    - Nouns : G-N.md
    - Numerals: G-NUM.md
    - Adjectives: G-ADJ.md
    - Adverbs: G-ADV.md
    - Verbs: G-V.md
    - Prepositions: G-PP.md
    - 'Sentence structure': G-P.md
    - 'Word building': G-AFX.md
  - Lessons:
    - Phrases: K-fraze.md
    - Course: K-kurse.md
  - Vocabulary:
    - "English–Panlingue": do_panlingue.md
    - "Panlingue–English": ze_panlingue.md
    - "Origins of words": lexaslia.md
    - Search: https://www.pandunia.info/panlingue/lexia/
  - 'About':
    - 'The idea': I-idea.md
    - Videos: I-filme.md
    - History: I-historia.md
    - 'Questions & Answers': FAQ.md
    - 'Adapting foreign words' : L02_lexe_modifikation.md
    - 'Translate this site': M01_trabashe.md
markdown_extensions:
  - toc:
      toc_depth: 2
extra_css:
    - assets/stile.css

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: eo
          name: Esperanto
          build: true
          site_name: "Panlingue lingvo"
          site_description: "Internacia helpa lingvo el la tuta mondo"
          nav_translations:
            Introduction: Enkonduko
            Grammar: Gramatiko
            "The 12 rules": "12 reguloj"
            "World Words": "Mondaj vortoj"
            "Spelling and pronunciation": "Literumo kaj prononco"
            "Regular Accent": "Regula akcento"
            Nouns : Substantivoj
            Numerals: Numeraloj
            Adjectives: Adjektivoj
            Adverbs: Adverboj
            Prepositions: Prepozicioj
            Pronouns: Pronomoj
            Verbs: Verboj
            "Sentence structure": "Fraza strukturo"
            "Word building": "Vortkonstruado"
            Lessons: Lecionoj
            Course: Kurso
            Phrases: Frazoj
            Vocabulary: Vortaro
            "English–Panlingue": "esperanto–panlingue"
            "Panlingue–English": "panlingue–esperanto"
            "About": Informoj
            "The idea": Ideo
        - locale: es
          name: Español
          build: true
          site_name: "Panlingue"
          site_description: "Lengua auxiliar internacional de origen global"
          nav_translations:
            Home: Inicio
            Introduction: Introducción
            Grammar: Gramática
            "The 12 rules": "12 reglas"
            "World Words": "Palabras del mundo"
            "Spelling and pronunciation": "Ortografía y pronunciación"
            "Regular Accent": "Acento regular"
            Nouns : Sustantivos
            Numerals: Numerales
            Adjectives: Adjetivos
            Adverbs: Adverbios
            Prepositions: Preposiciones
            Pronouns: Pronombres
            Verbs: Verbos
            "Sentence structure": "Estructura de la oración"
            "Word building": "Formación de palabras"
            Lessons: Lecciones
            Course: Curso
            Phrases: Frases
            Vocabulary: Vocabulario
            "English–Panlingue": "español–panlingue"
            "Panlingue–English": "panlingue–español"
            "About": "Acerca de"
            "The idea": Idea
        - locale: fr
          name: Français
          build: true
          site_name: "langue Panlingue"
          site_description: "langue auxiliaire internationale de source mondiale"
          nav_translations:
            Introduction: Introduction
            Grammar: Grammaire
            "The 12 rules": "12 règles"
            "World Words": "Mots du monde"
            "Spelling and pronunciation": "Orthographe et prononciation"
            "Regular Accent": "Accent régulier"
            Nouns : Noms
            Numerals: Numéraux
            Adjectives: Adjectifs
            Adverbs: Adverbes
            Prepositions: Prépositions
            Pronouns: Pronoms
            Verbs: Verbes
            "Sentence structure": "Structure de la phrase"
            "Word building": "Formation des mots"
            Lessons: Leçons
            Course: Cours
            Phrases: Phrases
            Vocabulary: Vocabulaire
            "English–Panlingue": "français–panlingue"
            "Panlingue–English": "panlingue–français"
            "About": À propos
            "The idea": Idée
        - locale: id
          name: Melayu
          build: true
          site_name: "Bahasa Panlingue"
          site_description: "Bahasa bantu antarabangsa berasaskan global"
          nav_translations:
            Introduction: Pengenalan
            Grammar: Tatabahasa
            "The 12 rules": "12 peraturan"
            "World Words": "Kata dunia"
            "Spelling and pronunciation": "Ejaan dan sebutan"
            "Regular Accent": "Aksen tetap"
            Nouns : Kata nama
            Numerals: Kata bilangan
            Adjectives: Kata sifat
            Adverbs: Kata keterangan
            Prepositions: Kata depan
            Pronouns: Kata ganti nama
            Verbs: Kata kerja
            "Sentence structure": "Struktur ayat"
            "Word building": "Pembentukan kata"
            Lessons: Pelajaran
            Course: Kursus
            Phrases: Frasa
            Vocabulary: Perbendaharaan kata
            "English–Panlingue": "melayu–panlingue"
            "Panlingue–English": "panlingue–melayu"
            "About": Tentang
            "The idea": Idea
        - locale: it
          name: Italiano
          build: true
          site_name: "Lingua Panlingue"
          site_description: "Lingua ausiliaria internazionale di origine globale"
          nav_translations:
            Introduction: Introduzione
            Grammar: Grammatica
            "The 12 rules": "12 regole"
            "World Words": "Parole del mondo"
            "Spelling and pronunciation": "Ortografia e pronuncia"
            "Regular Accent": "Accento regolare"
            Nouns : Sostantivi
            Numerals: Numerali
            Adjectives: Aggettivi
            Adverbs: Avverbi
            Prepositions: Preposizioni
            Pronouns: Pronomi
            Verbs: Verbi
            "Sentence structure": "Struttura della frase"
            "Word building": "Formazione delle parole"
            Lessons: Lezioni
            Course: Corso
            Phrases: Frasi
            Vocabulary: Vocabolario
            "English–Panlingue": "italiano–panlingue"
            "Panlingue–English": "panlingue–italiano"
            "About": Informazioni
            "The idea": Idea
        - locale: pl
          name: Polski
          build: true
          site_name: "Język Panlingue"
          site_description: "Międzynarodowy język pomocniczy o globalnym pochodzeniu"
          nav_translations:
            Introduction: Wprowadzenie
            Grammar: Gramatyka
            "The 12 rules": "12 zasad"
            "World Words": "Słowa świata"
            "Spelling and pronunciation": "Pisownia i wymowa"
            "Regular Accent": "Regularny akcent"
            Nouns : Rzeczowniki
            Numerals: Liczebniki
            Adjectives: Przymiotniki
            Adverbs: Przysłówki
            Prepositions: Przyimki
            Pronouns: Zaimek
            Verbs: Czasowniki
            "Sentence structure": "Struktura zdania"
            "Word building": "Tworzenie słów"
            Lessons: Lekcje
            Course: Kurs
            Phrases: Zwroty
            Vocabulary: Słownictwo
            "English–Panlingue": "polski–panlingue"
            "Panlingue–English": "panlingue–polski"
            "About": O języku
            "The idea": Pomysł
        - locale: pt
          name: Português
          build: true
          site_name: "Língua Panlingue"
          site_description: "Língua auxiliar internacional de origem global"
          nav_translations:
            Introduction: Introdução
            Grammar: Gramática
            "The 12 rules": "12 regras"
            "World Words": "Palavras do mundo"
            "Spelling and pronunciation": "Ortografia e pronúncia"
            "Regular Accent": "Acento regular"
            Nouns : Substantivos
            Numerals: Numerais
            Adjectives: Adjetivos
            Adverbs: Advérbios
            Prepositions: Preposições
            Pronouns: Pronomes
            Verbs: Verbos
            "Sentence structure": "Estrutura da frases"
            "Word building": "Formação de palavras"
            Lessons: Lições
            Course: Curso
            Phrases: Frases
            Vocabulary: Vocabulário
            "English–Panlingue": "português–panlingue"
            "Panlingue–English": "panlingue–português"
            "About": Sobre
            "The idea": Ideia
        - locale: fi
          name: Suomi
          build: true
          site_name: "Panlinguen kieli"
          site_description: "Finno-Ugric interlanguage"
          nav_translations:
            Introduction: Esittely
            Grammar: Kielioppi
            "The 12 rules": "12 sääntöä"
            "World Words": "Maailman sanat"
            "Spelling and pronunciation": "Äänne- ja kirjoitusasu"
            "Regular Accent": "Painotus"
            Nouns : Nimisant
            Numerals: Lukusanat
            Adjectives: Laatusanat
            Adverbs: Seikkasanat
            Prepositions: Suhdesanat
            Pronouns: Viittaussanat
            Verbs: Teonsanat
            "Sentence structure": Lauserakenne
            "Word building": "Sanojen johtaminen"
            Lessons: Oppitunnit
            Course: Kurssi
            Phrases: Lauseita
            Vocabulary: Sanasto
            "English–Panlingue": "suomi–panlingue"
            "Panlingue–English": "panlingue–suomi"
            "About": Tietoja
            "The idea": Idea
        - locale: ru
          name: Русский
          build: true
          site_name: "Язык Пангло"
          site_description: "Международный вспомогательный язык глобального происхождения"
          nav_translations:
            Introduction: Введение
            Grammar: Грамматика
            "The 12 rules": "12 правил"
            "World Words": "Мировые слова"
            "Spelling and pronunciation": "Правописание и произношение"
            "Regular Accent": "Регулярное ударение"
            Nouns : Существительные
            Numerals: Числительные
            Adjectives: Прилагательные
            Adverbs: Наречия
            Prepositions: Предлоги
            Pronouns: Местоимения
            Verbs: Глаголы
            "Sentence structure": "Структура предложения"
            "Word building": "Словообразование"
            Lessons: Уроки
            Course: Курс
            Phrases: Фразы
            Vocabulary: Словарь
            "English–Panlingue": "русский–пангло"
            "Panlingue–English": "пангло–русский"
            "About": О языке
            "The idea": Идея
        - locale: th
          name: ไทย
          build: true
          site_name: "ภาษาแปงโล"
          site_description: "ภาษาสากลเสริมระหว่างประเทศที่มีต้นกำเนิดทั่วโลก"
          nav_translations:
            Introduction: บทนำ
            Grammar: ไวยากรณ์
            "The 12 rules": "12 กฎ"
            "World Words": "คำจากทั่วโลก"
            "Spelling and pronunciation": "การสะกดคำและการออกเสียง"
            "Regular Accent": "การเน้นเสียงปกติ"
            Nouns : คำนาม
            Numerals: ตัวเลข
            Adjectives: คำคุณศัพท์
            Adverbs: คำวิเศษณ์
            Prepositions: คำบุพบท
            Pronouns: สรรพนาม
            Verbs: คำกริยา
            "Sentence structure": "โครงสร้างประโยค"
            "Word building": "การสร้างคำ"
            Lessons: บทเรียน
            Course: หลักสูตร
            Phrases: วลี
            Vocabulary: คำศัพท์
            "English–Panlingue": "ไทย–แปงโล"
            "Panlingue–English": "แปงโล–ไทย"
            "About": เกี่ยวกับ
            "The idea": แนวคิด
        - locale: ja
          name: 日本語
          build: true
          site_name: "パンデュニア語"
          site_description: "国際補助言語"
          nav_translations:
            Introduction: はじめに
            Grammar: 文法
            "The 12 rules": "12のルール"
            "World Words": "世界の言葉"
            "Spelling and pronunciation": "つづりと発音"
            "Regular Accent": "規則的なアクセント"
            Nouns : 名詞
            Numerals: 数詞
            Adjectives: 形容詞
            Adverbs: 副詞
            Prepositions: 前置詞
            Pronouns: 代名詞
            Verbs: 動詞
            "Sentence structure": "文の構造"
            "Word building": "語形成"
            Lessons: レッスン
            Course: コース
            Phrases: フレーズ
            Vocabulary: 語彙
            "English–Panlingue": "日本語–パンデュニア語"
            "Panlingue–English": "パンデュニア語–日本語"
            "About": 情報
            "The idea": アイデア
        - locale: zh
          name: 中文
          build: true
          site_name: "潘度尼亚语"
          site_description: "一种全球起源的国际辅助语言"
          nav_translations:
            Introduction: 介绍
            Grammar: 语法
            "The 12 rules": "12条规则"
            "World Words": "世界词汇"
            "Spelling and pronunciation": "拼写与发音"
            "Regular Accent": "规则重音"
            Nouns : 名词
            Numerals: 数词
            Adjectives: 形容词
            Adverbs: 副词
            Prepositions: 介词
            Pronouns: 代词
            Verbs: 动词
            "Sentence structure": "句子结构"
            "Word building": "构词法"
            Lessons: 课程
            Course: 课程
            Phrases: 短语
            Vocabulary: 词汇
            "English–Panlingue": "中文–潘度尼亚语"
            "Panlingue–English": "潘度尼亚语–中文"
            "About": 关于
            "The idea": 理念

# Customization
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
extra_css:
  - stile.css
