site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/pol
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../pol
site_dir: ../../html/pol
use_directory_urls: false
theme:
  name: material
  language: pl
  palette:
    primary: green
extra_css:
  - stile.css
nav:
    - Główna: 'index.md'
    - 'Info':
        - 'Wprowadzenie': I-idea.md
        - 'Założenia': I-filosofia.md
    - 'Nauka':
        - 'Rozmówki': K-fraze.md
        - 'Kurs': K-kurse.md
    - 'Gramatyka':
        - G-baze.md
        - G-ABC.md
        - G-N.md
        - G-ADJ.md
        - G-ADV.md
        - G-NUM.md
        - G-PRO.md
        - G-V.md
        - G-jumle.md
        - G-AFX.md
    - 'Słownik':
        - 'Panlingue-polski': panlingue-pol.md
        - 'Polski-panlingue': pol-panlingue.md
        - 'Etymologia': lexaslia.md
        - 'Wyszukaj': tiddly.html
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2
