site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/spa
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../spa
site_dir: ../../html/spa
use_directory_urls: false
theme:
  name: material
  language: es
  palette:
    primary: green
extra_css:
  - stile.css
nav:
    - Inicio: 'index.md'
    - 'Info':
        - 'Principios': I-filosofia.md
    - 'Lecciones':
        - 'Ortografía': G-ABC.md
        - 'Frases básicas': K-fraze.md
        - 'Curso': K-kurse.md
    - 'Diccionarios':
        - 'Panlingue-Español': panlingue-spa.md
        - 'Español-Panlingue': spa-panlingue.md
        - 'Diccionario etimologico': lexaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2

