site_name: 汎語
site_url: https://www.pandunia.info/panlingue/jpn
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../jpn
site_dir: ../../html/jpn
use_directory_urls: false
theme:
  name: material
  language: ja
  palette:
    primary: green
nav:
    - 'ホームページ': 'index.md'
    - '基本': G-baze.md
    - '文法':
        - G-PoS.md
        - G-N.md
        - G-ADJ.md
        - G-ADV.md
        - G-NUM.md
        - G-PRO.md
        - G-V.md
        - G-jumle.md
        - G-AFX.md
    - 'フレーズ集': K-fraze.md
    - '対話形式のレッスン': K-kurse.md
    - '辞典': panlingue-jpn.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2
