site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/panlingue
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../panlingue
site_dir: ../../html/panlingue
use_directory_urls: false
theme:
  name: material
  palette:
    primary: green
extra_css:
  - stile.css
nav:
    - ABC: abc.md
    - sage:
        - 'lili urse du tungi dante': urse_dante.md
        - 'tin buze e guye': 3_buze_e_guye.md
        - 'tin lili gurube': 3_lil_gurube.md
    - kitabe:
        - 'insan du putongi hake': putong_hake.md
        - 'dini kitabe': dini_kitabe.md
    - logoliste:
        - 'dexnam': dexonam.md
        - 'lexaslia': lexaslia.md
        - 'lexe du nume': loge_du_numbe.md
    - filme: filme.md
    - linke: linke.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2
