site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/fin
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../fin
site_dir: ../../html/fin
use_directory_urls: false
theme:
  name: material
  language: fi
  palette:
    primary: green
extra_css:
  - stile.css
plugins:
    - search:
        lang: fi
nav:
    - Kotisivu: 'index.md'
    - 'Tietoa':
        - 'Maailman yhteyskieli': I-idea.md
        - 'Kysymyksiä & vastauksia': FAQ.md
    - 'Panlinguen perusteet ja rakenne':
        - 'Perussäännöt': G-baze.md
        - 'Yleismaailmallinen sanasto': L-lexe.md
        - 'Ääntäminen': G-ABC.md
        - 'Sanaluokat': G-PoS.md
        - 'Substantiivit': G-N.md
        - 'Adjektiivit': G-ADJ.md
        - 'Adverbit': G-ADV.md
        - 'Numeraalit': G-NUM.md
        - 'Pronominit': G-PRO.md
        - 'Verbit': G-V.md
        - 'Lauserakenteita': G-jumle.md
    - 'Oppitunteja':
        - 'Lauseita': K-fraze.md
        - 'Kurssi': K-kurse.md
    - 'Sanasto':
        - 'Panlingue-suomi': panlingue-fin.md
        - 'Suomi-panlingue': fin-panlingue.md
        - 'Alkuperäsanasto': lexaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2
